INSERT INTO phong_gd (id_ten, ten_phgd) VALUES ('Không', 'nan');
INSERT INTO phong_gd (id_ten, ten_phgd) VALUES ('Q1', 'Phòng GDĐT quận 1');
INSERT INTO phong_gd (id_ten, ten_phgd) VALUES ('Q2', 'Phòng GDĐT quận 2');
INSERT INTO phong_gd (id_ten, ten_phgd) VALUES ('Q3', 'Phòng GDĐT quận 3');
INSERT INTO phong_gd (id_ten, ten_phgd) VALUES ('Q4', 'Phòng GDĐT quận 4');
INSERT INTO phong_gd (id_ten, ten_phgd) VALUES ('Q5', 'Phòng GDĐT quận 5');
INSERT INTO phong_gd (id_ten, ten_phgd) VALUES ('Q6', 'Phòng GDĐT quận 6');
INSERT INTO phong_gd (id_ten, ten_phgd) VALUES ('Q7', 'Phòng GDĐT quận 7');
INSERT INTO phong_gd (id_ten, ten_phgd) VALUES ('Q8', 'Phòng GDĐT quận 8');
INSERT INTO phong_gd (id_ten, ten_phgd) VALUES ('Q9', 'Phòng GDĐT quận 9');
INSERT INTO phong_gd (id_ten, ten_phgd) VALUES ('Q10', 'Phòng GDĐT quận 10');
INSERT INTO phong_gd (id_ten, ten_phgd) VALUES ('Q11', 'Phòng GDĐT quận 11');
INSERT INTO phong_gd (id_ten, ten_phgd) VALUES ('Q12', 'Phòng GDĐT quận 12');
INSERT INTO phong_gd (id_ten, ten_phgd) VALUES ('Bình Tân', 'Phòng GDĐT Bình Tân');
INSERT INTO phong_gd (id_ten, ten_phgd) VALUES ('Bình Thạnh', 'Phòng GDĐT Bình Thạnh');
INSERT INTO phong_gd (id_ten, ten_phgd) VALUES ('Gò Vấp', 'Phòng GDĐT Gò Vấp');
INSERT INTO phong_gd (id_ten, ten_phgd) VALUES ('Phú Nhuận', 'Phòng GDĐT Phú Nhuận');
INSERT INTO phong_gd (id_ten, ten_phgd) VALUES ('Tân Bình', 'Phòng GDĐT Tân Bình');
INSERT INTO phong_gd (id_ten, ten_phgd) VALUES ('Tân Phú', 'Phòng GDĐT Tân Phú');
INSERT INTO phong_gd (id_ten, ten_phgd) VALUES ('Bình Chánh', 'Phòng GDĐT Bình Chánh');
INSERT INTO phong_gd (id_ten, ten_phgd) VALUES ('Cần Giờ', 'Phòng GDĐT Cần Giờ');
INSERT INTO phong_gd (id_ten, ten_phgd) VALUES ('Củ Chi', 'Phòng GDĐT Củ Chi');
INSERT INTO phong_gd (id_ten, ten_phgd) VALUES ('Hóc Môn', 'Phòng GDĐT Hóc Môn');
INSERT INTO phong_gd (id_ten, ten_phgd) VALUES ('Nhà Bè', 'Phòng GDĐT Nhà Bè');
INSERT INTO phong_gd (id_ten, ten_phgd) VALUES ('Thủ Đức', 'Phòng GDĐT Thủ Đức');
